sonar.projectKey=iblog-monolith-go
sonar.projectName=iBlog Monolith Go

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,migrations/**,seed/**,cmd/seed/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.qualitygate.wait=true

